[project]
name = "wiz-remidiation"
version = "0.1.0"
description = "Autonomous Code Remediation System using AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.0.2",
    "mcp[cli]>=1.19.0",
]
